### ISSUE TITLE
nice layout of the header

### ISSUE THREAD

**Issue by mcollina** [GlenTiki/autocannon-reporter#11]
This is what it's there right now!

<img width="1220" alt="schermata 2016-08-01 alle 17 39 21" src="https://cloud.githubusercontent.com/assets/52195/17299515/e848c0ec-580e-11e6-9eee-4b8e5d2160cb.png">

**Comment by thekemkid** [comment]
I made that area the meta information, available at a glance, was unsure of how it could look

**Comment by afuechsel** [comment]
Should be closed with #18
